// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Storebook.Infra;

#nullable disable

namespace Storebook.Infra.Migrations
{
    [DbContext(typeof(StorebookContext))]
    partial class StorebookContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Storebook.Domain.Entities.Book", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("PageCount")
                        .HasColumnType("int");

                    b.Property<int>("PublicationYear")
                        .HasColumnType("int");

                    b.Property<string>("Publisher")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Author");

                    b.HasIndex("Title")
                        .IsUnique();

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Active = true,
                            Author = "Robert C. Martin",
                            CreatedOn = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            PageCount = 464,
                            PublicationYear = 2008,
                            Publisher = "Prentice Hall",
                            StockQuantity = 1,
                            Title = "Clean Code"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Active = true,
                            Author = "Eric Evans",
                            CreatedOn = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            PageCount = 560,
                            PublicationYear = 2003,
                            Publisher = "Addison-Wesley",
                            StockQuantity = 2,
                            Title = "Domain-Driven Design"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            Active = true,
                            Author = "Martin Fowler",
                            CreatedOn = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            PageCount = 448,
                            PublicationYear = 1999,
                            Publisher = "Addison-Wesley",
                            StockQuantity = 3,
                            Title = "Refactoring"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            Active = true,
                            Author = "Andrew Hunt",
                            CreatedOn = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            PageCount = 352,
                            PublicationYear = 1999,
                            Publisher = "Addison-Wesley",
                            StockQuantity = 4,
                            Title = "The Pragmatic Programmer"
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            Active = true,
                            Author = "GoF",
                            CreatedOn = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            PageCount = 395,
                            PublicationYear = 1994,
                            Publisher = "Addison-Wesley",
                            StockQuantity = 5,
                            Title = "Design Patterns"
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666666"),
                            Active = true,
                            Author = "Robert C. Martin",
                            CreatedOn = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            PageCount = 432,
                            PublicationYear = 2017,
                            Publisher = "Pearson",
                            StockQuantity = 6,
                            Title = "Clean Architecture"
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777777777"),
                            Active = true,
                            Author = "Michael Feathers",
                            CreatedOn = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            PageCount = 456,
                            PublicationYear = 2004,
                            Publisher = "Prentice Hall",
                            StockQuantity = 7,
                            Title = "Working Effectively with Legacy Code"
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-888888888888"),
                            Active = true,
                            Author = "Martin Fowler",
                            CreatedOn = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            PageCount = 533,
                            PublicationYear = 2002,
                            Publisher = "Addison-Wesley",
                            StockQuantity = 8,
                            Title = "Patterns of Enterprise Application Architecture"
                        },
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-999999999999"),
                            Active = true,
                            Author = "Eric Freeman",
                            CreatedOn = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            PageCount = 694,
                            PublicationYear = 2004,
                            Publisher = "O'Reilly",
                            StockQuantity = 9,
                            Title = "Head First Design Patterns"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Active = true,
                            Author = "Kyle Simpson",
                            CreatedOn = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            PageCount = 278,
                            PublicationYear = 2015,
                            Publisher = "O'Reilly",
                            StockQuantity = 10,
                            Title = "You Don’t Know JS"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
