// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Storebook.Infra;

#nullable disable

namespace Storebook.Infra.Migrations
{
    [DbContext(typeof(StorebookContext))]
    [Migration("20260208221555_M5")]
    partial class M5
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Storebook.Domain.Entities.Livro", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AnoPublicacao")
                        .HasColumnType("int");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("Autor")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTimeOffset>("DataCadastro")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Editora")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("QuantidadeEstoque")
                        .HasColumnType("int");

                    b.Property<int>("QuantidadePaginas")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Autor");

                    b.HasIndex("Titulo")
                        .IsUnique();

                    b.ToTable("Livros");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            AnoPublicacao = 2008,
                            Ativo = true,
                            Autor = "Robert C. Martin",
                            DataCadastro = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Editora = "Prentice Hall",
                            QuantidadeEstoque = 1,
                            QuantidadePaginas = 464,
                            Titulo = "Clean Code"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            AnoPublicacao = 2003,
                            Ativo = true,
                            Autor = "Eric Evans",
                            DataCadastro = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Editora = "Addison-Wesley",
                            QuantidadeEstoque = 2,
                            QuantidadePaginas = 560,
                            Titulo = "Domain-Driven Design"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            AnoPublicacao = 1999,
                            Ativo = true,
                            Autor = "Martin Fowler",
                            DataCadastro = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Editora = "Addison-Wesley",
                            QuantidadeEstoque = 3,
                            QuantidadePaginas = 448,
                            Titulo = "Refactoring"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            AnoPublicacao = 1999,
                            Ativo = true,
                            Autor = "Andrew Hunt",
                            DataCadastro = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Editora = "Addison-Wesley",
                            QuantidadeEstoque = 4,
                            QuantidadePaginas = 352,
                            Titulo = "The Pragmatic Programmer"
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            AnoPublicacao = 1994,
                            Ativo = true,
                            Autor = "GoF",
                            DataCadastro = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Editora = "Addison-Wesley",
                            QuantidadeEstoque = 5,
                            QuantidadePaginas = 395,
                            Titulo = "Design Patterns"
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666666"),
                            AnoPublicacao = 2017,
                            Ativo = true,
                            Autor = "Robert C. Martin",
                            DataCadastro = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Editora = "Pearson",
                            QuantidadeEstoque = 6,
                            QuantidadePaginas = 432,
                            Titulo = "Clean Architecture"
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777777777"),
                            AnoPublicacao = 2004,
                            Ativo = true,
                            Autor = "Michael Feathers",
                            DataCadastro = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Editora = "Prentice Hall",
                            QuantidadeEstoque = 7,
                            QuantidadePaginas = 456,
                            Titulo = "Working Effectively with Legacy Code"
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-888888888888"),
                            AnoPublicacao = 2002,
                            Ativo = true,
                            Autor = "Martin Fowler",
                            DataCadastro = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Editora = "Addison-Wesley",
                            QuantidadeEstoque = 8,
                            QuantidadePaginas = 533,
                            Titulo = "Patterns of Enterprise Application Architecture"
                        },
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-999999999999"),
                            AnoPublicacao = 2004,
                            Ativo = true,
                            Autor = "Eric Freeman",
                            DataCadastro = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Editora = "O'Reilly",
                            QuantidadeEstoque = 9,
                            QuantidadePaginas = 694,
                            Titulo = "Head First Design Patterns"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            AnoPublicacao = 2015,
                            Ativo = true,
                            Autor = "Kyle Simpson",
                            DataCadastro = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Editora = "O'Reilly",
                            QuantidadeEstoque = 10,
                            QuantidadePaginas = 278,
                            Titulo = "You Don’t Know JS"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
